<?php 
                $mahasiswa=array(
                'mhs1'=> array(
                        'nama'=>'rizal',
                        'nrp'=>1,
                        'ipk'=>3.1,
                        'rambut'=> 'hitam dan lurus',
                        'tinggi'=>160,
                        'berat'=>50,
                        'ket'=>'tidak cuti',
                        'dosen_wali'=>'Desy Intan Permatasari',
                        'kelas'=>'D4-A dan D4-B',
                        'nilaiMatkulKonsepPemrograman'=>'A',
                        'statusKeatifanDiHimit'=>'aktif',      
                
                ),
                'mhs2'=> array(
                        'nama'=>'dayat',
                        'nrp'=>2,
                        'ipk'=>3.2,
                        'rambut'=> 'hitam dan lurus',
                        'tinggi'=>160,
                        'berat'=>50,
                        'ket'=>'tidak cuti',
                        'dosen_wali'=>'Desy Intan Permatasari',
                        'kelas'=>'D4-A dan D4-B',
                        'nilaiMatkulKonsepPemrograman'=>'A',
                        'statusKeatifanDiHimit'=>'aktif',     
                ),
                'mhs3'=> array(
                        'nama'=>'andre',
                        'nrp'=>3,
                        'ipk'=>3.75,
                        'rambut'=> 'kuning dan lurus',
                        'tinggi'=>168,
                        'berat'=>80,
                        'ket'=>'cuti',
                        'dosen_wali'=>'Irul Kozikin',
                        'kelas'=>'D4-A dan D4-B',
                        'nilaiMatkulKonsepPemrograman'=>'B',
                        'statusKeatifanDiHimit'=>'aktif',    
                ),
                'mhs4'=> array(
                        'nama'=>'zaim',
                        'nrp'=>4,
                        'ipk'=>3.95,
                        'rambut'=> 'pink dan lurus',
                        'tinggi'=>190,
                        'berat'=>70,
                        'ket'=>'cuti',
                        'dosen_wali'=>'Afrizal Rizky',
                        'kelas'=>'D4-A dan D4-B',
                        'nilaiMatkulKonsepPemrograman'=>'A',
                        'statusKeatifanDiHimit'=>'tidak aktif',    
                ),
                );

?>